
version: '3'
services:
    cmake:
        image: 'indusninja/opengl'
        command: >
            sh -c "rm -rf build && mkdir build && cd build && cmake .. && make && make test"
        volumes:
            - .:/usr/src/myapp
        working_dir: /usr/src/myapp
